# Generated by Django 6.0.5 on 2026-05-17 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название направления')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание направления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='direction_icons/', verbose_name='Иконка направления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'направление фитнеса',
                'verbose_name_plural': 'направления фитнеса',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Название акции')),
                ('description', models.TextField(verbose_name='Описание акции')),
                ('discount_percent', models.PositiveIntegerField(default=10, verbose_name='Скидка, %')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'акция',
                'verbose_name_plural': 'акции',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО тренера')),
                ('specialization', models.CharField(max_length=150, verbose_name='Специализация')),
                ('experience', models.PositiveIntegerField(verbose_name='Опыт работы, лет')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trainer_photos/', verbose_name='Фото тренера')),
            ],
            options={
                'verbose_name': 'тренер',
                'verbose_name_plural': 'тренеры',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Тип тренировки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'тип тренировки',
                'verbose_name_plural': 'типы тренировок',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150, verbose_name='Имя клиента')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус заявки')),
                ('application_date', models.DateField(auto_now_add=True, verbose_name='Дата заявки')),
                ('total_price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличными'), ('card', 'Банковская карта'), ('online', 'Онлайн-оплата')], default='card', max_length=20, verbose_name='Способ оплаты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'заявка на абонемент',
                'verbose_name_plural': 'заявки на абонементы',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название абонемента')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL')),
                ('description', models.TextField(max_length=2500, verbose_name='Описание абонемента')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Срок действия, дней')),
                ('visits_count', models.PositiveIntegerField(default=12, verbose_name='Количество посещений')),
                ('image', models.ImageField(blank=True, null=True, upload_to='membership_images/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='club.fitnessdirection', verbose_name='Направление')),
                ('training_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='club.trainingtype', verbose_name='Тип тренировки')),
            ],
            options={
                'verbose_name': 'абонемент',
                'verbose_name_plural': 'абонементы',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150, verbose_name='Имя автора')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitness_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название занятия')),
                ('day_of_week', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=20, verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('hall', models.CharField(default='Основной зал', max_length=100, verbose_name='Зал')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_items', to='club.fitnessdirection', verbose_name='Направление')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_items', to='club.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'тип расписания',
                'verbose_name_plural': 'типы расписания',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150, verbose_name='Имя клиента')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('visit_date', models.DateTimeField(verbose_name='Дата и время посещения')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('visited', 'Посещено'), ('missed', 'Пропущено')], default='planned', max_length=20, verbose_name='Статус')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='club.fitnessdirection', verbose_name='Направление')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='club.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'посещение',
                'verbose_name_plural': 'посещения',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits_per_week', models.PositiveIntegerField(default=3, verbose_name='Посещений в неделю')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_memberships', to='club.application', verbose_name='Заявка')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_memberships', to='club.membership', verbose_name='Абонемент')),
            ],
            options={
                'verbose_name': 'абонемент в заявке',
                'verbose_name_plural': 'абонементы в заявках',
                'unique_together': {('application', 'membership')},
            },
        ),
        migrations.CreateModel(
            name='MembershipTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_trainers', to='club.membership', verbose_name='Абонемент')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_trainers', to='club.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'тренер абонемента',
                'verbose_name_plural': 'тренеры абонементов',
                'unique_together': {('trainer', 'membership')},
            },
        ),
    ]
